---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trust-id
  namespace: trustid-issuer # Must be in the same namespace than ingress
spec:
  secretName: wildcard-trustid-id-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.trustid.id"
  dnsNames:
  - "*.trustid.id"