apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-issuer-azure-kv
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: postgres-issuer-secrets
      type: Opaque
      data:
        - objectName: ISSUER-DB-USER
          key: POSTGRES_USER
        - objectName: ISSUER-DB-PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: ISSUER-DB-NAME
          key: POSTGRES_DB
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    clientID: {{ .Values.global.azure.managedIdentityClientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    tenantId: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: ISSUER-DB-USER
          objectType: secret
        - |
          objectName: ISSUER-DB-PASSWORD
          objectType: secret
        - |
          objectName: ISSUER-DB-NAME
          objectType: secret
