apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresIssuerNode.deployment.name }}
  labels:
    {{- include "trustid-issuer.postgresIssuerNode.deploymentLabels" . | nindent 4 }}
    {{- include "trustid-issuer.postgresIssuerNode.common.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.postgresIssuerNode.service.name }}
  replicas: {{ .Values.postgresIssuerNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "trustid-issuer.postgresIssuerNode.Labels" . | nindent 6 }}
      {{- include "trustid-issuer.postgresIssuerNode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustid-issuer.postgresIssuerNode.Labels" . | nindent 8 }}
        {{- include "trustid-issuer.postgresIssuerNode.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      containers:
        - name: {{ .Values.postgresIssuerNode.deployment.containerName }}
          image: {{ .Values.postgresIssuerNode.deployment.image.repository }}:{{ .Values.postgresIssuerNode.deployment.image.tag }}
          imagePullPolicy: {{ .Values.postgresIssuerNode.deployment.image.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.postgresIssuerNode.deployment.containerPort }}
          volumeMounts:
            {{- toYaml .Values.postgresIssuerNode.deployment.volumeMounts | nindent 12 }}
          env:
            - name: POSTGRES_USER_FILE
              value: /mnt/secrets-store/ISSUER-DB-USER
            - name: POSTGRES_PASSWORD_FILE
              value: /mnt/secrets-store/ISSUER-DB-PASSWORD
            - name: POSTGRES_DB_FILE
              value: /mnt/secrets-store/ISSUER-DB-NAME
            - name: POSTGRES_INITDB_ARGS
              value: "-A md5"
            - name: PGDATA
              value: /var/postgresql/data
      volumes:
        - name: {{ .Values.postgresIssuerNode.deployment.volumeName }}
          configMap:
            name: {{ .Values.postgresIssuerNode.deployment.postgresconfigMapRef }}
            items:
              - key: {{ .Values.postgresIssuerNode.deployment.items }}
                path: {{ .Values.postgresIssuerNode.deployment.items }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres-issuer-azure-kv
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgresIssuerNode.pvc.volumeName }}
        annotations:
          "helm.sh/resource-policy": keep
      spec:
        storageClassName: managed-csi-retain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgresIssuerNode.pvc.storageRequest }}
