apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.postgresIssuerNode.pvc.postgres }}
  labels:
  {{- include "trustid-issuer.postgresIssuerNode.common.labels" . | nindent 4 }} 
spec:
  storageClassName:  managed-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresIssuerNode.pvc.storageRequest }}