apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.postgresIssuerNode.pvc.postgres }}
  labels:
  {{- include "trustid-issuer.postgresIssuerNode.common.labels" . | nindent 4 }} 
spec:
  storageClassName:  managed-csi-retain
  volumeName: pvc-860c3185-d3d3-4333-8b8d-0c56e2d8b3cb  # Force bind to retained volume with data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresIssuerNode.pvc.storageRequest }}