apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: issuer-kv-tls
  namespace: trustid-issuer
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    tenantId: ""
    userAssignedIdentityClientID: ""  # Will be filled in
    keyvaultName: "issuer-kv"
    objects: |
      array:
        - |
          objectName: trustid-tls-cert
          objectType: secret
          objectFormat: pfx
  secretObjects:
  - secretName: issuer-tls-cert-kv
    type: kubernetes.io/tls
    data:
    - objectName: trustid-tls-cert
      key: tls.key
    - objectName: trustid-tls-cert
      key: tls.crt