apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-issuer-azure-kv
  namespace: trustid-issuer
spec:
  provider: azure
  secretObjects:
    - secretName: azure
      type: Opaque
      data:
        - objectName: PRIVATE-KEY
          key: PRIVATE_KEY
        - objectName: VAULT-PWD
          key: VAULT_PWD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.azure.managedIdentityClientId }}
    keyvaultName: {{ .Values.global.azure.keyVaultName }}
    tenantId: {{ .Values.global.azure.tenantId }}
    objects: |
      array:
        - |
          objectName: PRIVATE-KEY
          objectType: secret
        - |
          objectName: VAULT-PWD
          objectType: secret
