global:
  #== PROD: PRIVATE DNS ==
  uidomain: ui.issuernode.trustid.int.app 
  apidomain: api.issuernode.trustid.int.app 

  #== LOCAL: (testing with port fwd):
  # uidomain: ui.issuer.local
  # apidomain: api.issuer.local

issuernode_repository_image: issuer.azurecr.io/issuernode-api
issuernode_repository_tag: latest
issuernode_ui_repository_image: issuer.azurecr.io/issuernode-ui
issuernode_ui_repository_tag: latest
issuerUiInsecure: false
ingressEnabled: true
namespace: trustid-issuer
apiIssuerNode:
  deployment:
    replicaCount: 1
    name: api-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
      issuerApiAuthPassword: $(ISSUER_API_AUTH_PASSWORD)
    imagePullPolicy: Always
    labels:
      app: api-issuer-node-deployment
    livenessProbe:
      name: Custom-Header
      value: Awesome
      path: /status
      port: 3001
      initialDelaySeconds: 3
      periodSeconds: 60 
    apiconfigMapRef: issuer-node-api-configmap
    args: 
      - '"./migrate; ./platform"'
    command:  
      - '"sh", "-c"'
    containerPort: 3001
    containerName: api

  service:
    name: api-issuer-node-svc
    ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
    type: ClusterIP
    nodePort: 30001
    selector: api-issuer-node
    labels:
      app: issuer-node

  configMap:
    issuerApiAuthUser: user-issuer
    issuerCircuitPath: ./pkg/credentials/circuits
    # issuerDbName: platformid
    issuerDbPort: "5432"
    # issuerDbUser: polygonid
    issuerKMSBJJProvider: metakeep
    issuerKMSETHProvider: vault
    issuerKeyStorePluginIden3MountPath: iden3
    issuerKeyStorePort: "8200"
    issuerLogLevel: "-4"
    issuerLogMode: "2"
    issuerNativeProofGenerationEnabled: "true"
    issuerOnchainCheckStatusFrequency: 1m
    issuerOnchainPublishStateFrequency: 1m
    issuerPublishKeyPath: pbkey
    issuerRedisUrl: redis://redis-issuer-node-svc:6379/1
    issuerReverseHashServiceEnabled: "false"
    issuerServerPort: "3001"
    issuerVaultUserpassAuthEnabled: "true"
    issuerCredentialStatusPublishingKeyPath: pbkey
    issuerIpfsGatewayUrl: https://ipfs.io
    issuerKMSProviderLocalStorageFilePath: /localstoragekeys
    issuerDeepLinkServerUrl: "https://api.trustid.life/api"

notificationsIssuerNode:
  deployment:
    replicaCount: 1
    name: notifications-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
    imagePullPolicy: IfNotPresent
    labels: 
      app: notifications-issuer-node-deployment
    containerName: notifications
    args: 
      - '"./notifications"'
    command:  
      - '"sh", "-c"'

pendingPublisherIssuerNode:
  deployment:
    replicaCount: 1
    name: pending-publisher-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
    imagePullPolicy: Always
    labels: 
      app: pending-publisher-issuer-node-deployment
    containerName: pending-publisher
    args: 
      - '"./pending_publisher"'
    command:  
      - '"sh", "-c"'

uiIssuerNode:
  deployment:
    replicaCount: 1
    name: ui-issuer-node
    imagePullPolicy: Always
    uiconfigMapRef: issuer-node-ui-configmap
    containerName: ui
    containerPort: 80
    labels: 
      app: ui-issuer-node-deployment
  service:
    name: ui-issuer-node-svc
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
    type: ClusterIP
    nodePort: 30003
    selector: ui-issuer-node
  configMap:
    issuerApiAuthUser: user-issuer
    issuerApiUiIssuerName: $(ISSUERNAME)
    issuerUiAuthUsername: user-ui   
    issuerUiIpfsGatewayUrl: https://ipfs.io
    issuerApiUiName: issuer-node-ui-configmap
    issuerUiSchemaExplorerAndBuilderUrl: https://tools.privado.id

vaultIssuerNode:
  azure:
    enabled: true
    secretProviderClass: azure
    secrets:
      - objectName: PRIVATE-KEY
        objectType: secret
        envVar: PRIVATE_KEY

azure:
  managedIdentityClientId: ""
  tenantId: ""
  keyVaultName: ""      
  secrets:
    - name: PRIVATE-KEY
      envVar: PRIVATE_KEY
    - name: trustid-tls-cert
      envVar: TLS_CERT
    - name: VAULT-PWD
      envVar: VAULT_PWD
    - name: UI-PASSWORD
      envVar: UIPASSWORD
    - name: ISSUER-NAME
      envVar: ISSUERNAME
    - name: ISSUER-RESOLVER-FILE
      envVar: ISSUER_RESOLVER_FILE
    - name: ISSUER-DB-USER
      envVar: ISSUER_DB_USER
    - name: ISSUER-DB-PASSWORD
      envVar: ISSUER_DB_PASSWORD
    - name: ISSUER-DB-PORT
      envVar: ISSUER_DB_PORT
    - name: ISSUER-DB-NAME
      envVar: ISSUER_DB_NAME
    - name: ISSUER-API-AUTH-PASSWORD
      envVar: ISSUER_API_AUTH_PASSWORD
    - name: ISSUER-KEY-STORE-PORT
      envVar: ISSUER_KEY_STORE_PORT
    - name: METAKEEP-BJJ-APP-API-KEY
      envVar: METAKEEP_BJJ_APP_API_KEY
    - name: METAKEEP-BJJ-APP-API-SECRET
      envVar: METAKEEP_BJJ_APP_API_SECRET
    - name: eth-rpc-ca-bundle
      envVar: ETH_RPC_TLS_CERT

ingress-nginx:
  enabled: true
  global:
    azure:
      managedIdentityClientId: ""
      tenantId: ""
      keyVaultName: ""
