global:
  vaultpwd: "super-secret-pepe"

uiPassword: "ui-admin-pass"

privateKey: |
  -----BEGIN PRIVATE KEY-----
  (your key here)
  -----END PRIVATE KEY-----

issuerResolverFile: |
  (optional resolver JSON or string)

apiIssuerNode:
  configMap:
    issuerApiAuthPassword: "password-issuer"
    issuerDbPassword: "strongpasswordapp"

uiIssuerNode:
  configMap:
    issuerApiAuthPassword: "password-issuer"

azure:
  managedIdentityClientId: "<UAMI_CLIENT_ID>"       
  tenantId: "<AZURE_TENANT_ID>"                     
  keyVaultName: "<YOUR_KEYVAULT_NAME>"             

  secrets:
    - name: PRIVATE_KEY
    - name: VAULT_PWD
    - name: UIPASSWORD
    - name: ISSUERNAME
    - name: ISSUER_RESOLVER_FILE
