apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: issuer-node-secrets
      type: Opaque
      data:
{{- range .Values.azure.secrets }}
        - objectName: {{ .name }}
          key: {{ .envVar }}
{{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.managedIdentityClientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    cloudName: {{ .Values.azure.cloudName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
{{- range .Values.azure.secrets }}
        - objectName: {{ .name }}
          objectType: secret
{{- end }}
